spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true

server:
  port: 8083

security:
  oauth2:
    client:
      client-id: api-gateway
      client-secret: api-gateway-secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: htrltp://localhost:8080/oauth/authorize
      scope:
        - read
        - write
      authorized-grant-types:
        - password
        - refresh_token
      resource-ids:
        - apigateway
    resource:
      user-info-uri: http://localhost:8080/users/me

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

zuul:
  ignored-services: '*'
  routes:
    products:
      path: /products/**
      service-id: product
      strip-prefix: false
    customers:
      path: /customers/**
      service-id: customer
      strip-prefix: false
